import { BaseSchema } from '@adonisjs/lucid/schema'

export default class extends BaseSchema {
  protected tableName = 'reit_fundamental_indicators'

  async up() {
    this.schema.createTable(this.tableName, (table) => {
      table.increments('id')
      table.integer('ticker_id').unsigned().notNullable().comment('Foreign key referencing the tickers table.')
      table.foreign('ticker_id').references('id').inTable('tickers')
      table.decimal('price', 10, 2).comment('Current REIT price.')
      table.decimal('ffo_yield', 10, 5).comment('Funds From Operations yield representing the FFO relative to the REIT price.')
      table.decimal('dividend_yield', 10, 5).comment('Dividend yield representing the dividend income relative to the REIT price.')
      table.decimal('pb_ratio', 10, 2).comment('Price-to-Book ratio comparing the market value of the REIT to its book value.')
      table.decimal('market_value', 15, 2).comment('Market value of the REIT.')
      table.decimal('liquidity', 15, 2).comment('Liquidity indicating the trading volume or liquidity of the REIT.')
      table.integer('property_count').comment('Number of properties owned by the REIT.')
      table.decimal('price_per_sqm', 10, 2).comment('Price per square meter of the properties owned by the REIT.')
      table.decimal('rent_per_sqm', 10, 2).comment('Rent per square meter generated by the properties owned by the REIT.')
      table.decimal('cap_rate', 10, 5).comment('Capitalization rate indicating the expected rate of return on the REIT\'s properties.')
      table.decimal('avg_vacancy_rate', 10, 5).comment('Average vacancy rate of the properties owned by the REIT.')
      table.timestamp('created_at')
      table.timestamp('updated_at')
    })
  }

  async down() {
    this.schema.dropTable(this.tableName)
  }
}